
# MODE: (dev | prod)
mode: prod

cluster:
    bind_port: 2000
    discovery_host: 127.0.0.1:2000
    advertise_host: 127.0.0.1:2000

kv:
    enable_encryption: true
    persist_to_disk: false
    persist_path: kv.db

api:
    enable: true
    port: 80
    authentication: false
    enable_metrics: true

ui:
    enable: true
    port: 80
    authentication: false

ssl:
    enable: false
    ssl_port: 443
    ssl_certificate: my.crt
    ssl_key: my.key

performance:
    enable_metrics: true
    enable_http_logs: true
    buffer_size: 4096

auth:
    # token | basic | none
    provider: jwt